In [1]:
lst = [1, 2, 3]

In [2]:
lst

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
array_one = np.array(lst)

In [5]:
array_one

array([1, 2, 3])

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(5,5)

array([[0.7731257 , 0.82267556, 0.50257311, 0.79657326, 0.89752647],
       [0.93538537, 0.46241569, 0.80931819, 0.7608232 , 0.9421773 ],
       [0.13705729, 0.91889939, 0.57398042, 0.13554251, 0.0569983 ],
       [0.89476507, 0.63599263, 0.45763383, 0.25254391, 0.46041542],
       [0.26763941, 0.33121505, 0.03397352, 0.98530352, 0.65949676]])

In [13]:
np.random.randn(5,5)

array([[-1.15135644, -2.33040784, -1.12157543, -0.40024995,  0.3401671 ],
       [-1.51051754, -0.70999164, -1.71589554, -1.75694539, -0.03978515],
       [ 0.23451095,  0.31371   , -0.23972259, -0.18170287,  3.04036848],
       [ 0.74339837, -0.07060278,  0.78550167, -1.56001138,  0.70589639],
       [-2.42521171,  0.3230306 ,  0.72916133,  1.58020977, -0.53257069]])

In [19]:
np.linspace(1,10,4, endpoint=False)

array([1.  , 3.25, 5.5 , 7.75])

In [22]:
arr2 = np.random.randint(0,101,100)

In [23]:
arr2

array([ 57,  64,  98,  28,  86,  12,  57,  33,  15,  43,  93,  31,  67,
        61,  27,  61,  13,  31,  65,  23,  70,  31,  36,  58,  86,   5,
        55,  25, 100,  14,  23,  34,  38,   6,   0,  14,  90,  53,  30,
        91,  74,   9,  46,  72,  64,  84,  48,  97,   8,  94,  21,  78,
         7,  69,  83,  35,  70,  91,  15,  88,   3,  15,  35,  38,  79,
        42,  46,  66,  84,  14,  73,  71,   9,  30,  49,  62,  99,  23,
        47,  20,  34,  80,   4,  70,   1,  76,  47,  50,  26,  41,  68,
        85,  23,  51,  76,  34,  32,  78,  40,  41])

In [24]:
arr2.shape

(100,)

In [27]:
matrix_arr2 = arr2.reshape(10,10)

In [28]:
matrix_arr2

array([[ 57,  64,  98,  28,  86,  12,  57,  33,  15,  43],
       [ 93,  31,  67,  61,  27,  61,  13,  31,  65,  23],
       [ 70,  31,  36,  58,  86,   5,  55,  25, 100,  14],
       [ 23,  34,  38,   6,   0,  14,  90,  53,  30,  91],
       [ 74,   9,  46,  72,  64,  84,  48,  97,   8,  94],
       [ 21,  78,   7,  69,  83,  35,  70,  91,  15,  88],
       [  3,  15,  35,  38,  79,  42,  46,  66,  84,  14],
       [ 73,  71,   9,  30,  49,  62,  99,  23,  47,  20],
       [ 34,  80,   4,  70,   1,  76,  47,  50,  26,  41],
       [ 68,  85,  23,  51,  76,  34,  32,  78,  40,  41]])

In [29]:
matrix_arr2.max()

100

In [31]:
matrix_arr2.argmax()

28

In [52]:
matrix_arr2[2,8] = "yes"

ValueError: invalid literal for int() with base 10: 'yes'

In [43]:
matrix_arr2

array([[ 57,  64,  98,  28,  86,  12,  57,  33,  15,  43],
       [ 93,  31,  67,  61,  27,  61,  13,  31,  65,  23],
       [ 70,  31,  36,  58,  86,   5,  55,  25, 100,  14],
       [ 23,  34,  38,   6,   0,  14,  90,  53,  30,  91],
       [ 74,   9,  46,  72,  64,  84,  48,  97,   8,  94],
       [ 21,  78,   7,  69,  83,  35,  70,  91,  15,  88],
       [  3,  15,  35,  38,  79,  42,  46,  66,  84,  14],
       [ 73,  71,   9,  30,  49,  62,  99,  23,  47,  20],
       [ 34,  80,   4,  70,   1,  76,  47,  50,  26,  41],
       [ 68,  85,  23,  51,  76,  34,  32,  78,  40,  41]])

In [62]:
matrix_arr2[2,8] = str(matrix_arr2[2,8])

In [57]:
str(2)

'2'

In [60]:
matrix_arr2

array([[ 57,  64,  98,  28,  86,  12,  57,  33,  15,  43],
       [ 93,  31,  67,  61,  27,  61,  13,  31,  65,  23],
       [ 70,  31,  36,  58,  86,   5,  55,  25, 100,  14],
       [ 23,  34,  38,   6,   0,  14,  90,  53,  30,  91],
       [ 74,   9,  46,  72,  64,  84,  48,  97,   8,  94],
       [ 21,  78,   7,  69,  83,  35,  70,  91,  15,  88],
       [  3,  15,  35,  38,  79,  42,  46,  66,  84,  14],
       [ 73,  71,   9,  30,  49,  62,  99,  23,  47,  20],
       [ 34,  80,   4,  70,   1,  76,  47,  50,  26,  41],
       [ 68,  85,  23,  51,  76,  34,  32,  78,  40,  41]])

In [64]:
matrix_arr2[2,8]

108

In [102]:
arr3 = [1,2,3,4, 5, 6, 7, 8, 9, 10]

In [98]:
arr3

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [104]:
arr3.append("Yes")

In [103]:
arr3.pop()

10

In [105]:
arr3 = np.array(arr3)

In [106]:
arr3 = arr3.reshape(5,2)

In [107]:
arr3[4,1] = "no"

In [108]:
arr3

array([['1', '2'],
       ['3', '4'],
       ['5', '6'],
       ['7', '8'],
       ['9', 'no']], dtype='<U21')

In [110]:
matrix_1 = np.random.randn(5, 5)

In [113]:
matrix_2 = np.random.randint(1, 100, 25).reshape(5,5)

In [114]:
matrix_1

array([[ 2.4307097 ,  0.53762222, -0.98254404, -1.25471551, -0.86730083],
       [-1.20110388, -0.3352187 ,  0.92427923, -1.95120486, -1.00601765],
       [-0.19518499,  0.44342518,  0.43810882,  0.40885812, -0.79055575],
       [ 0.34157122,  0.41714034, -0.45835635, -1.11584716, -0.86980683],
       [ 1.34839907,  0.47658358,  3.16491619, -0.7162776 , -0.45567838]])

In [115]:
matrix_2

array([[72, 28, 29, 72, 20],
       [47, 47, 54, 71, 75],
       [87, 24, 95,  1, 81],
       [ 1, 34, 23, 77, 88],
       [ 7, 85, 37, 95, 50]])

In [119]:
matrix_1 ** matrix_2

array([[ 5.92628891e+27,  2.84028438e-08, -6.00079460e-01,
         1.24525781e+07,  5.79956299e-02],
       [-5.49903845e+03, -4.90260486e-23,  1.42354943e-02,
        -4.08793195e+20, -1.56826717e+00],
       [-1.85711303e-62,  3.33955398e-09,  8.91845681e-35,
         4.08858122e-01, -5.40172724e-09],
       [ 3.41571224e-01,  1.22912049e-13, -1.61314997e-08,
        -4.62980618e+03,  4.66882335e-06],
       [ 8.10455372e+00,  4.38350358e-28,  3.26138395e+18,
        -1.70895305e-14,  8.56882305e-18]])

In [123]:
matrix_1 = np.ones((5,5))

In [126]:
matrix_2 = np.eye(5)

In [142]:
matrix_3 = matrix_1 + matrix_2

In [151]:
matrix_3 * matrix_1

array([[2., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

In [129]:
matrix_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [147]:
matrix_3

array([[2., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

In [153]:
matrix_3[0,]= np.eye(5)[0,]

In [154]:
matrix_3

array([[1., 0., 0., 0., 0.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

In [155]:
array=np.arange(25).reshape(5,5)

In [217]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [232]:
vector=np.array([[0,0,0,0,0],[0,1,0,0,0],[0,0,0,0,0],[0,0,0,1,0],[0,0,0,0,0]]).reshape(5,5)

In [230]:
vector

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1]])

In [233]:
array @ vector

array([[ 0,  1,  0,  3,  0],
       [ 0,  6,  0,  8,  0],
       [ 0, 11,  0, 13,  0],
       [ 0, 16,  0, 18,  0],
       [ 0, 21,  0, 23,  0]])

In [231]:
vector @ array

array([[ 0,  1,  2,  3,  4],
       [ 0,  0,  0,  0,  0],
       [10, 11, 12, 13, 14],
       [ 0,  0,  0,  0,  0],
       [20, 21, 22, 23, 24]])

In [182]:
vector2= [0,1,0,1,0]

In [184]:
vector2=np.array(vector2)

In [185]:
vector2

array([0, 1, 0, 1, 0])

In [174]:
vector2 @ array

array([20, 22, 24, 26, 28])

In [186]:
vector2.dot(array)

array([20, 22, 24, 26, 28])

In [238]:
test_arr = np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])